# Generated by Django 3.2.6 on 2021-08-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('retailer', models.TextField(blank=True, null=True)),
                ('spider_name', models.TextField(blank=True, null=True)),
                ('retailer_sku', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('market', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('catergory', models.TextField(blank=True, null=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('environment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Skus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.TextField(blank=True, null=True)),
                ('out_of_stock', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('sku_id', models.IntegerField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('retailer_sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
            options={
                'db_table': 'skus',
            },
        ),
        migrations.CreateModel(
            name='ImageUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(blank=True, null=True)),
                ('retailer_sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
            options={
                'db_table': 'image_urls',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('retailer_sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
            options={
                'db_table': 'description',
            },
        ),
    ]
